export const SYSTEM_USER_TYPES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  BUSINESS: 'BUSINESS',
  STAFF: 'STAFF',
  CUSTOMER: 'CUSTOMER',
};

export const ACCOUNT_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  PENDING: 'PENDING',
  BLOCKED: 'BLOCKED',
  DELETED: 'DELETED',
  SUSPENDED: 'SUSPENDED',
};

export const STOCK_TRANSACTION_TYPES = {
  STOCK_IN: 'STOCK_IN',
  STOCK_OUT: 'STOCK_OUT',
  ASSIGNMENT: 'ASSIGNMENT',
  TRANSFER: 'TRANSFER',
  RETURN: 'RETURN',
  DAMAGE: 'DAMAGE',
  ADJUSTMENT: 'ADJUSTMENT',
  CORRECTION: 'CORRECTION',
  OPENING_STOCK: 'OPENING_STOCK',
  SOLD: 'SOLD',
};

export const STOCK_STATUS_TYPES = {
  AVAILABLE: 'AVAILABLE',
  RESERVED: 'RESERVED',
  BLOCKED: 'BLOCKED',
  DAMAGED: 'DAMAGED',
  RETURNED: 'RETURNED',
  IN_TRANSIT: 'IN_TRANSIT',
  SOLD: 'SOLD',
};
